### ISSUE TITLE
Binary file in repo

### ISSUE THREAD

**Issue by zenermerps** [RaLazo/IPS#1]
Please remove the binary file you have added and add a proper `.gitignore`.

**Comment by RaLazo** [comment]
It is done Asneee my Brother #mansnothot

**Comment by zenermerps** [comment]
2 plus 2 is 4, minus 1 is 3, quick maffss

**Comment by RaLazo** [comment]
Gardenholes?

**Comment by RaLazo** [comment]
You Girl?
